version: "3.8"
services:
  ######################################################################################
  ## Container for ROS-Bloom deb package generation
  ## command: sudo docker-compose up ros-bloom
  ## Args:  - ROS_DISTRIBUTION=kinetic | meliodic | noetic
  ##        - BUILD_TYPE= devel | install
  ######################################################################################
  ros-bloom:
    build:
      context: .
      dockerfile: Dockerfile.bloom
      args:
        - ROS_DISTRIBUTION=kinetic
        - BUILD_TYPE=devel
    container_name: ros-devel
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - "./src:/root/catkin_ws/src:rw"
    command: bash
